"""
Django settings for ShoeStore project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x!x8ut%!h_*#i32_+%i6$kx$uolg01^3l@4yj_0)nlcfx^ke(='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'users',
    'products',
    'categorys',
    'cart',
    'orders',
    'payments',
    'brands.apps.BrandsConfig',
    'channels',
    'discounts',
    'chat',
]


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # 1 là DB index, có thể đổi thành 0,2,...
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# ASGI application
ASGI_APPLICATION = 'ShoeStore.asgi.application'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'       # sau khi login → trang chủ
LOGOUT_REDIRECT_URL = '/' 
AUTH_USER_MODEL = 'users.User'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.RedirectToPreviousMiddleware',
]

ROOT_URLCONF = 'ShoeStore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShoeStore.wsgi.application'

# Channel layers cho Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ShoeStore',      # tên database MySQL
        'USER': 'root',              # user MySQL
        'PASSWORD': 'root', # mật khẩu
        'HOST': 'localhost',         # hoặc IP server MySQL
        'PORT': '3306',              # port mặc định của MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AVATAR_PATH = 'avatars/default_avatar.png'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Đường dẫn để Django tìm các file tĩnh ngoài ứng dụng
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SESSION_SAVE_EVERY_REQUEST = True

# VNPAY CONFIG
VNPAY_RETURN_URL = 'http://localhost:8000/payment/payment_return'  # get from config
VNPAY_PAYMENT_URL = 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'  # get from config
VNPAY_API_URL = 'https://sandbox.vnpayment.vn/merchant_webapi/api/transaction'
VNPAY_TMN_CODE = 'YCWWRHWC'  # Website ID in VNPAY System, get from config
VNPAY_HASH_SECRET_KEY = 'M2SHPUB1NC2KTVTTWEHOF8IVA2527W7V'  # Secret key for create checksum,get from config

#cho phép gửi cookie sau khi redirect vể từ VNPAY
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False 
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# ===== External API config (loaded from static/data/openapi.json if present) =====
EXTERNAL_API_BASE_URL = None
EXTERNAL_API_TOKEN = None
EXTERNAL_ADDRESS_ENDPOINT = None  # e.g., '/v1/address/resolve'

try:
    spec_path = BASE_DIR / 'static' / 'data' / 'openapi.json'
    if spec_path.exists():
        with open(spec_path, encoding='utf-8') as f:
            openapi_spec = json.load(f)
            # Try common places for servers/base URL per OpenAPI 3
            servers = openapi_spec.get('servers') or []
            if servers and isinstance(servers, list):
                url = servers[0].get('url')
                if isinstance(url, str) and url:
                    EXTERNAL_API_BASE_URL = url.rstrip('/')
            # Optional: read token from extension fields if present
            # e.g., x-auth or components.securitySchemes
            x_auth = openapi_spec.get('x-auth') or {}
            token = x_auth.get('token')
            if isinstance(token, str) and token:
                EXTERNAL_API_TOKEN = token
            # Optional: endpoint path for address resolution
            x_endpoints = openapi_spec.get('x-endpoints') or {}
            addr_ep = x_endpoints.get('addressResolve')
            if isinstance(addr_ep, str) and addr_ep:
                EXTERNAL_ADDRESS_ENDPOINT = addr_ep
except Exception:
    # Keep defaults if spec cannot be parsed; avoid crashing settings
    pass
