# Generated by Django 5.2.5 on 2025-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên thương hiệu')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Đường dẫn SEO')),
            ],
            options={
                'verbose_name': 'Thương hiệu',
                'verbose_name_plural': 'Thương hiệu',
                'ordering': ['name'],
            },
        ),
    ]
