# Generated by Django 5.2.5 on 2025-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
        ('products', '0006_productreview_reviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chương trình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Số tiền cố định')], default='percentage', max_length=10, verbose_name='Loại giảm giá')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('min_order_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Áp dụng cho đơn hàng từ')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số tiền giảm tối đa')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Giảm giá tự động',
                'verbose_name_plural': 'Giảm giá tự động',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'phần trăm'), ('fixed', 'cố định')], default='percentage', max_length=10, verbose_name='Loại giảm giá')),
                ('value', models.DecimalField(decimal_places=2, help_text='Phần trăm hoặc số tiền cố định tùy loại', max_digits=10, verbose_name='giá trị giảm')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá trị đơn hàng tối thiểu')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Chỉ áp dụng cho giảm giá theo phần trăm', max_digits=10, null=True, verbose_name='Số tiền giảm tối đa (nếu áp dụng)')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('max_usage', models.PositiveIntegerField(default=1, verbose_name='Số lần sử dụng tối đa')),
                ('current_usage', models.PositiveIntegerField(default=0, verbose_name='Số lần đã sử dụng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='categorys.category', verbose_name='Áp dụng cho danh mục')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Áp dụng cho sản phẩm')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
            },
        ),
    ]
