# Generated by Django 5.2.5 on 2025-08-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_size'),
        ('products', '0005_size_remove_product_sizes_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
