# Generated by Django 5.2.5 on 2025-08-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_items',
            field=models.ManyToManyField(to='cart.cartitem'),
        ),
    ]
